#!/usr/bin/env python3
"""Render 8-ball animation frames and emit them as LVGL 9 I1 image arrays.

Usage: python3 tools/gen_eight_ball.py
Writes boards/shields/dongle_display/widgets/eight_ball_images.c and
tools/eight_ball_sheet.png. Pixel value 255 = lit (LVGL index 1, "black").
"""
import math
from pathlib import Path

from PIL import Image, ImageDraw

SIZE = 40
FRAMES = 12
SUPERSAMPLE = 8
BALL_R = 19.0      # outer radius of the ball
RING_W = 1.5       # lit outline thickness
DISC_R = 7.0       # white disc holding the "8"
ORBIT_R = 10.0     # distance of the disc center from the ball center
EIGHT_R = 2.6      # radius of each ring of the "8"
EIGHT_W = 1.1      # stroke of the "8" rings
EIGHT_GAP = 2.4    # half distance between the two ring centers

ROOT = Path(__file__).resolve().parent.parent
C_OUT = ROOT / "boards" / "shields" / "dongle_display" / "widgets" / "eight_ball_images.c"
SHEET_OUT = ROOT / "tools" / "eight_ball_sheet.png"


def _circle(draw, cx, cy, r, fill):
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=fill)


def render_frame(index: int, size: int = SIZE, frames: int = FRAMES) -> Image.Image:
    s = SUPERSAMPLE
    big = size * s
    img = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(img)
    c = big / 2.0
    theta = 2.0 * math.pi * index / frames

    # lit outline ring, dark body
    _circle(d, c, c, BALL_R * s, 255)
    _circle(d, c, c, (BALL_R - RING_W) * s, 0)

    # lit disc orbiting the center (in-plane rotation, like a wheel from the side)
    dx = c + ORBIT_R * s * math.sin(theta)
    dy = c - ORBIT_R * s * math.cos(theta)
    _circle(d, dx, dy, DISC_R * s, 255)

    # dark "8": two rings stacked along the radial direction so the glyph turns with the ball
    ux, uy = math.sin(theta), -math.cos(theta)  # radial unit vector (center -> disc)
    for sign in (-1, 1):
        ex = dx + sign * EIGHT_GAP * s * ux
        ey = dy + sign * EIGHT_GAP * s * uy
        _circle(d, ex, ey, EIGHT_R * s, 0)
        _circle(d, ex, ey, (EIGHT_R - EIGHT_W) * s, 255)

    small = img.resize((size, size), Image.LANCZOS)
    return small.point(lambda v: 255 if v >= 128 else 0).convert("1")


def frame_to_i1_bytes(img: Image.Image) -> bytes:
    w, h = img.size
    stride = (w + 7) // 8
    out = bytearray([0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0xFF])
    px = img.load()
    for y in range(h):
        row = bytearray(stride)
        for x in range(w):
            if px[x, y]:
                row[x // 8] |= 0x80 >> (x % 8)
        out += row
    return bytes(out)


def write_c_file(path: Path, frames) -> None:
    lines = [
        "/*",
        " * Generated by tools/gen_eight_ball.py. Do not edit by hand.",
        " * SPDX-License-Identifier: MIT",
        " */",
        "",
        "#include <lvgl.h>",
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
    ]
    for i, img in enumerate(frames):
        data = frame_to_i1_bytes(img)
        w, h = img.size
        name = f"eight_ball_{i:02d}"
        lines.append(f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {name}_map[] = {{")
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[:4]) + ", \t/*Color of index 0*/")
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[4:8]) + ", \t/*Color of index 1*/")
        lines.append("")
        stride = (w + 7) // 8
        body = data[8:]
        for y in range(h):
            row = body[y * stride:(y + 1) * stride]
            lines.append("  " + ", ".join(f"0x{b:02x}" for b in row) + ",")
        lines.append("};")
        lines.append("")
        lines.append(f"const lv_img_dsc_t {name} = {{")
        lines.append("  .header.cf = LV_COLOR_FORMAT_I1,")
        lines.append(f"  .header.w = {w},")
        lines.append(f"  .header.h = {h},")
        lines.append(f"  .data_size = {len(data)},")
        lines.append(f"  .data = {name}_map,")
        lines.append("};")
        lines.append("")
    path.write_text("\n".join(lines) + "\n")


def write_sheet(path: Path, frames) -> None:
    n = len(frames)
    w, h = frames[0].size
    scale = 4
    sheet = Image.new("L", (n * (w + 2) * scale, (h + 2) * scale), 64)
    for i, f in enumerate(frames):
        up = f.convert("L").resize((w * scale, h * scale), Image.NEAREST)
        sheet.paste(up, ((i * (w + 2) + 1) * scale, scale))
    sheet.save(path)


def main() -> None:
    frames = [render_frame(i) for i in range(FRAMES)]
    write_c_file(C_OUT, frames)
    write_sheet(SHEET_OUT, frames)
    print(f"wrote {C_OUT.relative_to(ROOT)} and {SHEET_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
